### ISSUE TITLE
Crash in Android before 4.4

### ISSUE THREAD

**Issue by Magolac** [TVerbaere/PFE#10]
The service crashes in devices with Android SDK before 4.4.

The exception trace:
`FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: android.util.ArrayMap
            at iagl.pfe.deactivation.util.Tools.getCurrentActivity(Tools.java:36)
            at iagl.pfe.deactivation.NetworkBroadcastReceiver.onReceive(NetworkBroadcastReceiver.java:20)
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2424)
            at android.app.ActivityThread.access$1500(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)`

**Comment by TVerbaere** [comment]
Logically it's solved ;)

**Comment by Magolac** [comment]
The problem is not solved. For example, in the test app, when clicking in the menu item "First" the app freezes.
The log prints this message: "Could not find class 'android.util.ArrayMap', referenced from method iagl.pfe.deactivation.util.Tools.getCurrentActivity"

**Comment by TVerbaere** [comment]
Ok, I look at this.

**Comment by TVerbaere** [comment]
Ah ! it's a bug I had introduced to test the UncaughtExceptionHandler! 
I will remove these :+1:
